// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_image_info`, `get_orientation`, `is_image`

List<ImageFile> getAllImage({
  required String folder,
  required List<ImageFile> existImages,
}) => RustLib.instance.api.crateApiFileGetAllImage(
  folder: folder,
  existImages: existImages,
);
