// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

class ImageFile {
  final String id;
  final String name;
  final String folder;
  final String path;
  final int width;
  final int height;
  final ImageOrientation orientation;
  final int size;

  const ImageFile({
    required this.id,
    required this.name,
    required this.folder,
    required this.path,
    required this.width,
    required this.height,
    required this.orientation,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      folder.hashCode ^
      path.hashCode ^
      width.hashCode ^
      height.hashCode ^
      orientation.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageFile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          folder == other.folder &&
          path == other.path &&
          width == other.width &&
          height == other.height &&
          orientation == other.orientation &&
          size == other.size;
}

enum ImageOrientation { all, landscape, portrait, square, other }
