// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`

class ImageFile {
  final String id;
  final String name;
  final String folder;
  final String path;
  final int width;
  final int height;
  final ImageOrientation orientation;
  final int modified;
  final int size;
  String blurhash;
  bool like;

  ImageFile({
    required this.id,
    required this.name,
    required this.folder,
    required this.path,
    required this.width,
    required this.height,
    required this.orientation,
    required this.modified,
    required this.size,
    required this.blurhash,
    required this.like,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      folder.hashCode ^
      path.hashCode ^
      width.hashCode ^
      height.hashCode ^
      orientation.hashCode ^
      modified.hashCode ^
      size.hashCode ^
      blurhash.hashCode ^
      like.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageFile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          folder == other.folder &&
          path == other.path &&
          width == other.width &&
          height == other.height &&
          orientation == other.orientation &&
          modified == other.modified &&
          size == other.size &&
          blurhash == other.blurhash &&
          like == other.like;
}

enum ImageOrientation { all, landscape, portrait, square, other }

class ScanResult {
  final List<ImageFile> added;
  final List<ImageFile> changed;

  const ScanResult({required this.added, required this.changed});

  @override
  int get hashCode => added.hashCode ^ changed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          changed == other.changed;
}
